#!/usr/bin/env python

"""
rewrite prepbufr file, skipping message subsets that meet certain criteria

(used to create a prepbufr file for a data denial experiment that excludes
data from the El Nino Rapid Response field program in 2016)
"""

from __future__ import print_function
import ncepbufr
import numpy as np
import sys


if len(sys.argv) < 3:
    raise SystemExit('prepbufr_rewrite <input prepbufr> <output prepbufr>')

# input and output file names from command line args.
prepbufr_in = sys.argv[1]
prepbufr_out = sys.argv[2]
if prepbufr_in == prepbufr_out:
    raise IOError('cannot overwrite input prepbufr file')

# open prepbufr file input file.
bufrin = ncepbufr.open(prepbufr_in)

# dump prepbufr table from input file.
bufrin.dump_table('prepbufr.table') 

# open output bufr file using same prepbufr table.
bufrout = ncepbufr.open(prepbufr_out,'w','prepbufr.table')

# mnemonic to extract data from subset headers.
hdstr='RSRD EXPRSRD'

nmsg = 0
nskip = 0
while bufrin.advance() == 0: # loop over messages.
    nmsg += 1
    bufrout.open_message(bufrin.msg_type,bufrin.msg_date) # open message
    #print(nmsg,bufrin.msg_type,bufrin.msg_date)
    while bufrin.load_subset() == 0: # loop over subsets in message.
        # read subset header from bufrin
        hdr = bufrin.read_subset(hdstr).squeeze()
        hdr = hdr.filled(0)
        rsrd = int(hdr[0])
        exprsrd = int(hdr[1])
        # skip restricted data with exp time > 10 days
        if rsrd != 0 and exprsrd > 240 : 
            nskip += 1
            continue
        # copy entire subset from bufrin to bufrout and write to message.
        bufrout.copy_subset(bufrin)
    bufrout.close_message() # close message

# close files.
if nskip > 0: print('%s skipped %s subsets' % (bufrin.msg_date,nskip))
bufrin.close(); bufrout.close()
